name: Quality Checks
on: [pull_request, create]

jobs:
  build:
    name: Quality (clippy, rustfmt)
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
        experimental: [false]
        include:
          - rust: beta
            target: aarch64-unknown-linux-gnu
            experimental: true
          - rust: beta
            target: aarch64-unknown-linux-musl
            experimental: true
          - rust: beta
            target: x86_64-unknown-linux-gnu
            experimental: true
          - rust: beta
            target: x86_64-unknown-linux-musl
            experimental: true
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust toolchain (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy

      - name: Check all commits build
        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
        run: |
          set -e
          commits=$(git rev-list origin/${{ github.base_ref }}..${{ github.sha }})
          for commit in $commits; do git checkout $commit; cargo check --tests --all --target=${{ matrix.target }}; done
          git checkout ${{ github.sha }}

      - name: Formatting (rustfmt)
        run: cargo fm1t -- --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.target != 'x86_64-unknown-linux-gnu' }}
          command: clippy
          args: --target=${{ matrix.target }} --locked --all --all-targets --tests -D warnings -D clippy::undocumented_unsafe_blocks

      - name: Check build did not modify any files
        run: test -z "$(git status --porcelain)"
