name: Unit tests
on: [pull_request, create]

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
        experimental: [false]
        include:
          - rust: beta
            target: x86_64-unknown-linux-gnu
            experimental: true
          - rust: beta
            target: x86_64-unknown-linux-musl
            experimental: true
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Rust toolchain (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy
      - name: Unit tests
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.target != 'x86_64-unknown-linux-gnu' }}
          command: test
          args: --target=${{ matrix.target }} --locked --all --all-targets --no-default-features --tests -D warnings -D clippy::undocumented_unsafe_blocks
